<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../Jellyfin.Plugin.CinematicUI.csproj" />
    <PackageReference Include="Jellyfin.Controller" Version="12.1.0" />
    <PackageReference Include="Jellyfin.Model" Version="12.1.0" />
  </ItemGroup>
</Project>
