// Native control shape observed in Jellyfin Web v12.1; synthetic media and handlers.
const icons = {play_arrow:'M8 5v14l11-7z',pause:'M6 5h4v14H6zm8 0h4v14h-4z',skip_previous:'M6 5h2v14H6zm3 7 10-7v14z',skip_next:'M16 5h2v14h-2zM5 5l10 7-10 7z',fast_rewind:'M11 5v14L1 12zm11 0v14l-10-7z',fast_forward:'m2 5 10 7-10 7zm11 0 10 7-10 7z',closed_caption:'M3 5h18v14H3zM5 9v6h5v-2H7v-2h3V9zm9 0v6h5v-2h-3v-2h3V9z',audiotrack:'M12 3h8v4h-5v11a4 4 0 1 1-3-4z',volume_up:'M3 9h4l5-4v14l-5-4H3zm12-3a7 7 0 0 1 0 12v-3a4 4 0 0 0 0-6z',settings:'M9 2h6l1 4 4 1 2 5-2 5-4 1-1 4H9l-1-4-4-1-2-5 2-5 4-1z',picture_in_picture_alt:'M2 4h20v16H2zm12 8h6v6h-6z',fullscreen:'M3 3h7v2H5v5H3zm11 0h7v7h-2V5h-5zM3 14h2v5h5v2H3zm16 0h2v7h-7v-2h5z',favorite:'M12 21 2 11C-2 2 8 0 12 6 16 0 26 2 22 11z',arrow_back:'M20 11H7l5-5-1-2-8 8 8 8 1-2-5-5h13z'};
const icon = name => `<svg class="material-icons ${name}" aria-hidden="true" viewBox="0 0 24 24"><path d="${icons[name]}"/></svg>`;
const button = (cls,label,glyph,extra='') => `<button class="${cls} autoSize paper-icon-button-light ${extra}" title="${label}" aria-label="${label}">${icon(glyph)}</button>`;
const range = (cls,label,value) => `<div class="sliderContainer mdl-slider-container ${cls === 'osdVolumeSlider' ? 'osdVolumeSliderContainer' : 'flex-grow'}"><input type="range" min="0" max="100" step="1" value="${value}" class="mdl-slider ${cls}" aria-label="${label}"><div class="mdl-slider-background-flex-container"><div class="mdl-slider-background-upper"></div><div class="mdl-slider-background-lower"></div></div></div>`;
exports.markup = `<div id="videoOsdPage" class="page libraryPage" data-type="video-osd"><div class="videoOsdBottom videoOsdBottom-maincontrols"><div class="osdControls">
  <div class="osdTextContainer osdMainTextContainer"><h3 class="osdTitle"></h3><div class="osdMediaStatus hide">Fetching additional data</div></div><div class="osdTextContainer osdSecondaryMediaInfo hide"></div>
  <div class="flex flex-direction-row align-items-center" dir="ltr"><div class="osdTextContainer startTimeText osdPositionText">0:00</div>${range('osdPositionSlider','Playback position',0)}<div class="osdTextContainer endTimeText osdDurationText">1:00</div></div>
  <div class="buttons focuscontainer-x"><div dir="ltr">${button('btnPreviousTrack','Skip to previous','skip_previous','hide')}${button('btnRewind','Rewind','fast_rewind')}${button('btnPause','Play','play_arrow')}${button('btnFastForward','Fast-forward','fast_forward')}${button('btnNextTrack','Skip to next','skip_next')}</div><div class="osdTimeText"><span class="endsAtText">Ends at 9:33 PM</span></div>${button('btnUserRating','Add to favorites','favorite')}${button('btnSubtitles','Subtitles','closed_caption')}${button('btnAudio','Audio','audiotrack')}<div class="volumeButtons">${button('buttonMute','Mute','volume_up')}${range('osdVolumeSlider','Volume',100)}</div>${button('btnVideoOsdSettings','Settings','settings')}${button('btnPip','Picture in picture','picture_in_picture_alt')}${button('btnFullscreen','Full screen','fullscreen')}</div>
  </div></div></div>`;
exports.style = `
  body:not(.playerFixture) .backgroundContainer{display:none}
  .fixtureDriver{position:fixed;right:0;top:50%;width:1px;height:1px;padding:0;border:0;opacity:0;z-index:9999}#fixtureShowControls{top:52%}
  .videoPlayerContainer{position:fixed;inset:0;background:#000;z-index:0}.htmlvideoplayer{width:100%;height:100%;object-fit:contain}.backgroundContainer{position:fixed;inset:0;background:#0d0d0f;z-index:1;pointer-events:none}.backgroundContainer-transparent{background:transparent}.playerFixture #fixtureApp{position:relative;z-index:2}.playerFixture #fixtureSpacer{display:none}.playerFixture #fixturePage{height:100dvh;background:transparent}.playerFixture .libraryPage{overflow:visible;padding:0}.playerFixture .mainAnimatedPages{height:100%}
  .playerFixture .skinHeader.osdHeader{height:7.5em;min-height:0;position:fixed;background:linear-gradient(#101010b8,transparent);box-shadow:none;backdrop-filter:none;pointer-events:none;z-index:3}.videoOsd-appBar{display:flex;align-items:center;height:48px;gap:12px;padding:0 16px}.videoOsd-appBar p{flex:1}.videoOsd-appBar button{pointer-events:auto;color:#eee;background:transparent;border:0;width:44px;height:44px}.videoOsd-appBar svg{width:24px;height:24px;fill:currentColor}
  .videoOsdBottom{position:fixed;bottom:0;left:0;right:0;display:flex;justify-content:center;pointer-events:none;color:#fff;padding:7.5em 0 1.75em;background:linear-gradient(transparent,#101010b8);transition:opacity .3s}.videoOsdBottom-hidden{opacity:0;pointer-events:none}.osdHeader-hidden{opacity:0}.osdControls{pointer-events:auto;flex:1;padding:0 .8em}.videoOsdBottom .buttons{display:flex;flex-wrap:wrap;align-items:center;padding:.25em 0 0}.paper-icon-button-light{display:inline-flex;align-items:center;justify-content:center;width:48px;height:48px;color:#fff;background:transparent;border:0;border-radius:50%;cursor:pointer}.material-icons{width:24px;height:24px;fill:currentColor}.osdTextContainer{display:flex;align-items:center;margin-bottom:.7em;padding-left:.5em}.osdMainTextContainer{align-items:baseline}.osdTitle{margin:0 1em 0 0}.osdMediaStatus{margin-left:auto}.volumeButtons{display:flex;align-items:center;margin:0 1em 0 .29em}.osdVolumeSliderContainer{width:9em;flex:1}.volumeButtons>.sliderContainer{width:9em}.osdTimeText{margin:0 auto 0 1em}.flex-direction-row{display:flex}.align-items-center{align-items:center}.sliderContainer{position:relative;flex:1;height:24px;margin:0 12px}.sliderContainer input{position:relative;width:100%;height:24px;margin:0;appearance:none;background:transparent;cursor:pointer;z-index:1}.sliderContainer input::-webkit-slider-runnable-track{background:transparent;height:3px}.sliderContainer input::-webkit-slider-thumb{appearance:none;width:10px;height:10px;border-radius:50%;background:#eee;margin-top:-3px}.mdl-slider-background-flex-container{position:absolute;left:0;right:0;top:11px;height:3px;background:#ffffff40;pointer-events:none}.mdl-slider-background-upper{position:absolute;inset:0;width:65%;background:#ffffff33}.mdl-slider-background-lower{position:absolute;inset:0;width:20%;background:#00a4dc}.playerFixture .fixtureMenu{left:auto;right:16px;top:auto;bottom:160px;max-width:calc(100vw - 32px)}
  @media(max-width:800px){.videoOsdBottom .btnFastForward,.videoOsdBottom .btnRewind{display:none}}
  @media(max-width:688px){.videoOsdBottom .volumeButtons{display:none}}
  @media(max-width:480px){.videoOsdBottom .btnUserRating{display:none}}
`;
exports.setup = function setupPlayer() {
  const page = document.querySelector('#videoOsdPage'), video = document.querySelector('.htmlvideoplayer');
  const pause = page.querySelector('.btnPause'), position = page.querySelector('.osdPositionSlider'), volume = page.querySelector('.osdVolumeSlider');
  const sync = () => { const label=video.paused?'Play':'Pause';pause.setAttribute('aria-label',label);pause.title=label;pause.querySelector('svg').innerHTML=video.paused?'<path d="M8 5v14l11-7z"/>':'<path d="M6 5h4v14H6zm8 0h4v14h-4z"/>';position.value=video.currentTime/60*100;page.querySelector('.osdPositionText').textContent='0:'+Math.floor(video.currentTime).toString().padStart(2,'0'); };
  pause.addEventListener('click',()=>video.paused?video.play():video.pause());
  video.addEventListener('play',sync);video.addEventListener('pause',sync);video.addEventListener('timeupdate',sync);
  position.addEventListener('input',()=>{video.currentTime=Number(position.value)/100*60;});
  volume.addEventListener('input',()=>{video.volume=Number(volume.value)/100;});
  page.querySelector('.buttonMute').addEventListener('click',()=>{video.muted=!video.muted;});
  page.querySelector('.btnRewind').addEventListener('click',()=>{video.currentTime=Math.max(0,video.currentTime-10);});
  page.querySelector('.btnFastForward').addEventListener('click',()=>{video.currentTime=Math.min(59,video.currentTime+10);});
  page.querySelector('.btnNextTrack').addEventListener('click',()=>{document.querySelector('.videoOsd-appBar>p').textContent='Northern Lights — S1:E2 — A New Horizon';video.currentTime=0;});
  page.querySelector('.btnFullscreen').addEventListener('click',()=>document.fullscreenElement?document.exitFullscreen():document.documentElement.requestFullscreen());
  page.querySelector('.btnPip').addEventListener('click',()=>document.pictureInPictureElement?document.exitPictureInPicture():video.requestPictureInPicture());
  for(const cls of ['btnSubtitles','btnAudio','btnVideoOsdSettings']) page.querySelector('.'+cls).addEventListener('click',e=>{
    const menu=document.createElement('div');menu.className='fixtureMenu';menu.setAttribute('role','dialog');menu.setAttribute('aria-label',e.currentTarget.title);menu.innerHTML='<p>'+e.currentTarget.title+' native controls</p><button>Close</button>';menu.querySelector('button').onclick=()=>menu.remove();document.body.appendChild(menu);
  });
  document.querySelector('.videoOsd-appBar button').addEventListener('click',()=>{video.pause();location.hash='#/home';});
  document.querySelector('#fixtureHideControls').addEventListener('click',()=>page.querySelector('.videoOsdBottom').classList.add('videoOsdBottom-hidden','hide'));
  document.querySelector('#fixtureShowControls').addEventListener('click',()=>page.querySelector('.videoOsdBottom').classList.remove('videoOsdBottom-hidden','hide'));
};
